name: Next Build
on:
  pull_request:
    branches:
      - main
  workflow_call:

permissions: {}
jobs:
  lint:
    permissions:
      contents: read
    uses: ./.github/workflows/lint.yml
  build:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@cb605e52c26070c328afc4562f0b4ada7618a84e # v2.10.4
        with:
          egress-policy: audit
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - uses: oven-sh/setup-bun@4bc047ad259df6fc24a6c9b0f9a0cb08cf17fbe5 # v2.0.1
        with:
          bun-version-file: ".bun-version"
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Build
        run: bun run build
